name: mopub_flutter
description: A plugin for Mopub Banner, Interstitial & Rewarded Ads in Android & iOS
version: 1.2.2+1

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mopub_flutter
        pluginClass: MopubFlutterPlugin
      ios:
        pluginClass: MopubFlutterPlugin
